apiVersion: apps/v1
kind: Deployment
metadata:
name: boardgame-deployment
namespace: default
spec:
selector:
matchLabels:
app: boardgame
replicas: 2
template:
metadata:
labels:
app: boardgame
spec:
  template:
    spec:
      containers:
        - image: rakesh5293/java-gihub:0cf3756
containers:
  - name: boardgame
image: rakesh5293/java-gihub:1c891a4
imagePullPolicy: Always
ports:
  - containerPort: 8080
