apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      containers:
        - name: boardgame
          image: rakesh5293/java-gihub:caba486
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
